# Generated by Django 5.2.8 on 2025-12-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eys", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
    ]
