# Generated by Django 5.2.8 on 2025-11-17 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('instructor', models.ForeignKey(blank=True, limit_choices_to={'role__name__in': ['Regular Instructor', 'Advisor Instructor', 'Head of Department']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_given', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(blank=True, limit_choices_to={'role__name': 'Student'}, related_name='courses_taken', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
