# Generated by Django 5.2.8 on 2025-12-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eys", "0002_alter_user_options_user_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="dark_mode",
            field=models.BooleanField(default=False),
        ),
    ]
