# Generated by Django 5.2.4 on 2025-12-29 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eys', '0003_user_advisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='advisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__name__in': ['Regular Instructor', 'Advisor Instructor', 'Head of Department']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisees', to=settings.AUTH_USER_MODEL),
        ),
    ]
