# Generated by Django 5.2.8 on 2025-11-17 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eys', '0004_learningoutcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamLOWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eys.exam')),
                ('learning_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eys.learningoutcome')),
            ],
        ),
    ]
