# Generated by Django 5.2.4 on 2025-12-29 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eys', '0004_user_advisor_note'),
        ('eys', '0005_alter_user_advisor'),
    ]

    operations = [
    ]
