# Generated by Django 5.2.8 on 2025-11-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eys', '0005_examloweight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='weight',
        ),
        migrations.AddField(
            model_name='exam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
