# Generated by Django 5.2.8 on 2025-11-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eys', '0006_remove_exam_weight_exam_created_at_exam_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningoutcome',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
