# Generated by Codex on 2025-12-29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("eys", "0006_merge_0004_user_advisor_note_0005_alter_user_advisor"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgrammingOutcome",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=20, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="LOPOWeight",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("weight", models.FloatField()),
                ("learning_outcome", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="po_weights", to="eys.learningoutcome")),
                ("programming_outcome", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lo_weights", to="eys.programmingoutcome")),
            ],
            options={
                "unique_together": {("learning_outcome", "programming_outcome")},
            },
        ),
    ]
