# Generated by Codex on 2025-12-29

from django.db import migrations


def seed_programming_outcomes(apps, schema_editor):
    ProgrammingOutcome = apps.get_model("eys", "ProgrammingOutcome")
    items = []
    for num in range(3, 15):
        code = f"PO{num}"
        title = f"Program Outcome {num}"
        items.append((code, title))
    for code, title in items:
        ProgrammingOutcome.objects.get_or_create(
            code=code,
            defaults={"title": title, "description": ""},
        )


def unseed_programming_outcomes(apps, schema_editor):
    ProgrammingOutcome = apps.get_model("eys", "ProgrammingOutcome")
    ProgrammingOutcome.objects.filter(code__in=[f"PO{n}" for n in range(3, 15)]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("eys", "0007_programming_outcome_lopo_weight"),
    ]

    operations = [
        migrations.RunPython(seed_programming_outcomes, unseed_programming_outcomes),
    ]
