# Generated by Django 5.2.8 on 2025-11-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eys', '0008_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningoutcome',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
