# Generated by Django 5.2.8 on 2025-12-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eys', '0011_alter_announcement_options_announcement_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='announcements/'),
        ),
    ]
