# Generated by Django 5.2.4 on 2025-12-04 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eys', '0014_assignment_notification_submission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='allow_late',
            new_name='is_group',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='late_penalty',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='is_late',
        ),
        migrations.AddField(
            model_name='submission',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='AssignmentCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('max_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('order', models.PositiveIntegerField(default=1)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='eys.assignment')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='eys.assignment')),
                ('members', models.ManyToManyField(blank=True, related_name='assignment_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('assignment', 'name')},
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='eys.assignmentgroup'),
        ),
        migrations.CreateModel(
            name='SubmissionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='submission_attachments/')),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='eys.submission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionCriterionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('feedback', models.TextField(blank=True)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='eys.assignmentcriterion')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_scores', to='eys.submission')),
            ],
            options={
                'unique_together': {('submission', 'criterion')},
            },
        ),
    ]
