# Generated by Django 5.2.8 on 2025-12-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eys', '0016_assignmenttemplate_coursematerial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentgroup',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='assignmentcriterion',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='submissioncriterionscore',
            name='criterion',
        ),
        migrations.AlterUniqueTogether(
            name='assignmentgroup',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='assignmentgroup',
            name='members',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='group',
        ),
        migrations.RemoveField(
            model_name='assignmenttemplate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='coursematerial',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursematerial',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='submission',
            name='graded_by',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='student',
        ),
        migrations.RemoveField(
            model_name='submissionattachment',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='submissioncriterionscore',
            name='submission',
        ),
        migrations.AlterUniqueTogether(
            name='submissioncriterionscore',
            unique_together=None,
        ),
        migrations.AddField(
            model_name='course',
            name='threshold_high',
            field=models.IntegerField(default=80, help_text="Bu puanın üstü 'İstikrarlı' olarak etiketlenir.", verbose_name='Üst Başarı Sınırı'),
        ),
        migrations.AddField(
            model_name='course',
            name='threshold_low',
            field=models.IntegerField(default=60, help_text="Bu puanın altı 'Destek Gerekli' olarak etiketlenir.", verbose_name='Alt Başarı Sınırı'),
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='AssignmentCriterion',
        ),
        migrations.DeleteModel(
            name='AssignmentGroup',
        ),
        migrations.DeleteModel(
            name='AssignmentTemplate',
        ),
        migrations.DeleteModel(
            name='CourseMaterial',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='SubmissionAttachment',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
        migrations.DeleteModel(
            name='SubmissionCriterionScore',
        ),
    ]
