# Generated by Django 5.2.4 on 2025-12-15 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eys', '0018_coursethreshold'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='course',
                    name='threshold_high',
                ),
                migrations.RemoveField(
                    model_name='course',
                    name='threshold_low',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='coursethreshold',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='Assignment',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('title', models.CharField(max_length=200)),
                        ('description', models.TextField(blank=True)),
                        ('due_at', models.DateTimeField(blank=True, null=True)),
                        ('is_group', models.BooleanField(default=False)),
                        ('max_score', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                        ('attachment', models.FileField(blank=True, null=True, upload_to='assignments/')),
                        ('published_at', models.DateTimeField(blank=True, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='eys.course')),
                        ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_created', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'ordering': ['-published_at', '-created_at'],
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='AssignmentCriterion',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('title', models.CharField(max_length=200)),
                        ('max_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                        ('order', models.PositiveIntegerField(default=1)),
                        ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='eys.assignment')),
                    ],
                    options={
                        'ordering': ['order', 'id'],
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='AssignmentGroup',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=100)),
                        ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='eys.assignment')),
                        ('members', models.ManyToManyField(blank=True, related_name='assignment_groups', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'ordering': ['name'],
                        'unique_together': {('assignment', 'name')},
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='AssignmentTemplate',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('title', models.CharField(max_length=200)),
                        ('description', models.TextField(blank=True)),
                        ('max_score', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                        ('attachment', models.FileField(blank=True, null=True, upload_to='assignment_templates/')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_templates', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'ordering': ['-created_at'],
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='CourseMaterial',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('week', models.PositiveIntegerField(default=1)),
                        ('title', models.CharField(max_length=200)),
                        ('description', models.TextField(blank=True)),
                        ('attachment', models.FileField(blank=True, null=True, upload_to='course_materials/')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='eys.course')),
                        ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials_created', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'ordering': ['course_id', 'week', '-created_at'],
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='Notification',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('kind', models.CharField(choices=[('new_assignment', 'New Assignment'), ('assignment_due', 'Assignment Due Soon'), ('submission_received', 'Submission Received'), ('submission_graded', 'Submission Graded'), ('announcement_comment', 'Announcement Comment')], max_length=50)),
                        ('message', models.CharField(max_length=255)),
                        ('url', models.CharField(blank=True, default='', max_length=255)),
                        ('payload', models.TextField(blank=True, default='')),
                        ('is_read', models.BooleanField(default=False)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('read_at', models.DateTimeField(blank=True, null=True)),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'ordering': ['-created_at'],
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='Submission',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('submitted_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('file', models.FileField(blank=True, null=True, upload_to='submissions/')),
                        ('text', models.TextField(blank=True)),
                        ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                        ('feedback', models.TextField(blank=True)),
                        ('graded_at', models.DateTimeField(blank=True, null=True)),
                        ('version', models.PositiveIntegerField(default=1)),
                        ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='eys.assignment')),
                        ('graded_by', models.ForeignKey(blank=True, limit_choices_to={'role__name__in': ['Regular Instructor', 'Advisor Instructor', 'Head of Department']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL)),
                        ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='eys.assignmentgroup')),
                        ('student', models.ForeignKey(limit_choices_to={'role__name': 'Student'}, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'ordering': ['-updated_at'],
                        'unique_together': {('assignment', 'student')},
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='SubmissionAttachment',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('file', models.FileField(upload_to='submission_attachments/')),
                        ('version', models.PositiveIntegerField(default=1)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='eys.submission')),
                    ],
                    options={
                        'ordering': ['-created_at'],
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='SubmissionCriterionScore',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                        ('feedback', models.TextField(blank=True)),
                        ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='eys.assignmentcriterion')),
                        ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_scores', to='eys.submission')),
                    ],
                    options={
                        'unique_together': {('submission', 'criterion')},
                    },
                ),
            ],
        ),
    ]
